# AZURE STORAGE
AZURE_STORAGE_CONNECTION_STRING="DefaultEndpointsProtocol=https;AccountName=ruleaistorage;AccountKey=u0B2C1sDI+CnvuX1XGzCArb7pWE+SwFuassBlDhKDIGM5Ure4vDRvPUV5WNVhCcz7ASLpJoMWUpN+AStqAVKSQ==;EndpointSuffix=core.windows.net"

# AZURE OPENAI CONFIG
AZURE_OPENAI_API_KEY=""
AZURE_OPENAI_ENDPOINT=" "
AZURE_OPENAI_API_VERSION=""
AZURE_OPENAI_CHAT_DEPLOYMENT="gpt-40"

# ADD THE EMBEDDING MODEL CONFIG
AZURE_OPENAI_EMBEDDING_DEPLOYMENT="text-embedding-3-small"

# AZURE AI SEARCH -- KNOWLEDGE BASE CONFIG
AZURE_SEARCH_ENDPOINT=""